# Generated by Django 3.2.7 on 2021-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parseresults',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='parseresults',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parseresults',
            name='image',
            field=models.ImageField(upload_to='wordclouds/'),
        ),
    ]
