# Generated by Django 3.2.7 on 2021-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0002_auto_20210926_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parseresults',
            options={'ordering': ('time',)},
        ),
        migrations.AddField(
            model_name='parseresults',
            name='posts_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
